function[trimesh]=gid2mat(gidmesh)
%=====================================================
%function[trimesh]=gid2mat(gidmesh)
%
% Convert from GiD mesh format into matlab format
% 
% Input:
%   gidmesh: gid mesh file generated by GiD
%
% Output:
%   trimesh: structure of output matlab format mesh
%            trimesh=struct('tri',{},'x',{},'y',{});
%            tri: m-by-3 matrix for triangular connectivity
%            x/y: n-by-1 matrix for x and y coordinates
% 
% Hua Wang @ Uni Leeds, 22/10/2009
%=====================================================

%open gid mesh file
fid = fopen(gidmesh,'r');
if fid<0
  error([gidmesh ' can not be opened!']);
end

while (feof(fid)==0)
  %read coordinates of the nodes
  strline = fgetl(fid);
  if strcmpi(strline,'coordinates')==1
    strline = fgetl(fid);
    while strcmpi(strline,'end coordinates')==0
      [id,x(id,1),y(id,1),z(id,1)]=strread(strline,'%d %f %f %f');
      strline = fgetl(fid);
    end
  end

  %read triangulars
  if strcmpi(strline,'elements')==1
    strline = fgetl(fid);
    while strcmpi(strline,'end elements')==0
      [id,tri(id,1),tri(id,2),tri(id,3)]=strread(strline,'%d %d %d %d');
      strline = fgetl(fid);
    end
  end

  if strcmpi(strline,'end elements')==1
    break;
  end
end
fclose(fid);

trimesh.tri=tri;
trimesh.x=x;
trimesh.y=y;

%quickplot - JWeiss
%trisurf(trimesh.tri,trimesh.x,trimesh.y,zeros(size(trimesh.x)));
